packages:
  - packages/*

catalog:
  '@antfu/eslint-config': 6.7.3
  '@types/node': 22.13.1
  '@vitest/coverage-v8': 4.0.16
  eslint: 9.39.2
  picocolors: 1.1.1
  tsdown: 0.15.6
  tsx: 4.19.2
  typescript: 5.7.3
  vitest: 4.0.16
