packages:
  - packages/*

catalog:
  '@antfu/eslint-config': 3.16.0
  '@types/node': 22.13.1
  '@vitest/coverage-v8': 3.2.4
  eslint: 9.19.0
  tsdown: 0.15.6
  tsx: 4.19.2
  typescript: 5.7.3
  vitest: 3.2.4
