packages:
  - packages/*
  - apps/*

catalog:
  '@antfu/eslint-config': 6.7.3
  '@types/node': 22.13.1
  '@vitest/coverage-v8': 4.0.16
  eslint: 9.39.2
  picocolors: 1.1.1
  tsdown: 0.15.12
  tsx: 4.21.0
  typescript: 5.9.3
  vitepress: 2.0.0-alpha.15
  vitest: 4.0.16
