name: CI - Async Context Plugin

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-async-context-plugin:
    name: CI - Async Context Plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/async-context-plugin

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Run linters
        run: pnpm lint

      # Needed as the logger is a dependency of the async context plugin
      - name: Build logger
        run: pnpm -F @crowlog/logger build

      - name: Type check
        run: pnpm typecheck

      - name: Run unit test
        run: pnpm test

      - name: Build the app
        run: pnpm build